import Head from 'next/head'
import Link from 'next/link'

const Nosotros = () => {
  return (
    <div>
        <Head>
        <title>Guitar LA NEXT-JS - Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Desde nosotros</h1>
      <Link href="/">Ir a inicio</Link>
    </div>
  )
}

export default Nosotros
